require:
  - rubocop-rails
  - rubocop-rspec

Lint/Debugger:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'config'

Metrics:
  Enabled: false

Rails/UnknownEnv:
  Environments: ['development', 'test', 'production', 'demo', 'qa']

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 200

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false