require:
  - rubocop-rails
  - rubocop-rspec

Lint/Debugger:
  Exclude:
    - 'spec/rails_helper.rb'

# wanted
Metrics/BlockLength:
  Max: 400

# wanted
Metrics/MethodLength:
  Max: 20

# Offense count: 4
# Configuration parameters: Environments.
# Environments: development, test, production
Rails/UnknownEnv:
  Environments: ['development', 'test', 'production', 'demo', 'qa']

# Offense count: 8
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/errors_controller.rb'
    - 'app/controllers/pages_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'db/migrate/20211105150000_add_sessions_table.rb'
    - 'db/migrate/20211105150006_create_delayed_jobs.rb'

# wanted
Layout/LineLength:
  Max: 200
