require:
  - rubocop-rails
  - rubocop-rspec

Lint/Debugger:
  Exclude:
    - 'spec/rails_helper.rb'

Metrics/BlockLength:
  Max: 400

Metrics/MethodLength:
  Max: 20

Rails/UnknownEnv:
  Environments: ['development', 'test', 'production', 'demo', 'qa']

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 200

