development:
  adapter: postgresql
  database: team05_dev_2
  min_messages: warning
  
  # uncomment these lines if you are connected to postgres over the network stack
  # host: localhost
  # username:
  # password:

test:
  adapter: postgresql
  database: team05_test_2
  min_messages: warning

  # uncomment these lines if you are connected to postgres over the network stack
  # host: localhost
  # username:
  # password:
